# Generated by Django 5.1.5 on 2025-02-05 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
    ]
